# Generated by Django 5.1.3 on 2026-04-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
