# Generated by Django 5.1.3 on 2026-04-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0002_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='license',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
