# Generated by Django 5.1.3 on 2026-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0003_remove_agreement_license_remove_agreement_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='serial_no',
            field=models.CharField(blank=True, help_text='Serial number for tracking individual items', max_length=100),
        ),
    ]
