# Generated by Django 5.1.3 on 2026-05-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0004_purchaseorderitem_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='serial_no',
        ),
    ]
