# Generated by Django 5.1.3 on 2026-04-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='password_chars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
