# Generated by Django 5.1.3 on 2026-04-18 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_password_chars_to_login_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='olmsuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='olmsuser',
            name='army_no',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Army number must start with MT, MTM, P, or PW followed by digits. E.g. MT 134513, MTM 456, P 789, PW 101.', regex='^(MTM|MT|PW|P)\\s?\\d+$')]),
        ),
        migrations.AlterField(
            model_name='olmsuser',
            name='member_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('lecturer', 'Instructor'), ('staff', 'School Staff')], max_length=10, null=True),
        ),
    ]
