# Generated by Django 5.1.3 on 2026-05-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_virtualcard_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcard',
            name='card_no',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated card number e.g. MSICT-LIB-26-000001', max_length=25, null=True, unique=True),
        ),
    ]
