# Generated by Django 5.1.3 on 2026-05-19 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_virtualcard_card_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ranks',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='olmsuser',
            name='password_changed_after_first_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olmsuser',
            name='rank',
            field=models.ForeignKey(blank=True, db_column='rank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.rank'),
        ),
    ]
