# Generated by Django 5.1.3 on 2026-05-19 09:39

from django.db import migrations

RANKS = [
    'GENERAL', 'LIEUTENANT GENERAL', 'MAJOR GENERAL', 'BRIGADIER GENERAL',
    'COLONEL', 'LIEUTENANT COLONEL', 'MAJOR', 'CAPTAIN',
    'LIEUTENANT', 'SECOND LIEUTENANT',
    'WI', 'WII', 'SSGT', 'SGT', 'CPL', 'PTE',
]


def seed_ranks(apps, schema_editor):
    Rank = apps.get_model('accounts', 'Rank')
    for name in RANKS:
        Rank.objects.get_or_create(rank_name=name)


def unseed_ranks(apps, schema_editor):
    Rank = apps.get_model('accounts', 'Rank')
    Rank.objects.filter(rank_name__in=RANKS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_rank_lostfine_pwflag'),
    ]

    operations = [
        migrations.RunPython(seed_ranks, reverse_code=unseed_ranks),
    ]
