# Generated by Django 5.1.3 on 2026-05-22 15:48

from django.db import migrations


def set_existing_users_active(apps, schema_editor):
    """Set all existing users to active status (only public registrations should be pending)."""
    OLMSUser = apps.get_model('accounts', 'OLMSUser')
    OLMSUser.objects.filter(account_status='pending').update(account_status='active')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_olmsuser_account_status_olmsuser_approved_at_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_users_active, migrations.RunPython.noop),
    ]
