# Generated by Django 5.1.3 on 2026-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20260522_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olmsuser',
            old_name='rejection_reason',
            new_name='cancelled_reason',
        ),
        migrations.RemoveField(
            model_name='olmsuser',
            name='account_status',
        ),
        migrations.AddField(
            model_name='olmsuser',
            name='card_no',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated card number e.g. MSICT-2026-00001', max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='olmsuser',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
