# Generated by Django 5.1.3 on 2026-07-02

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_olmsuser_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olmsuser',
            name='army_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Army number must start with MT, MTM, P, or PW followed by digits. E.g. MT 134513, MTM 456, P 789, PW 101.', regex='^(MTM|MT|PW|P)\\s?\\d+$')]),
        ),
        migrations.AlterField(
            model_name='olmsuser',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('guest_auto', 'Guest Auto Approved')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='olmsuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='olmsuser',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olmsuser',
            name='total_guest_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='olmsuser',
            name='total_guest_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
