# Generated by Django 5.1.3 on 2026-07-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_guest_foundation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_in_time', models.DateTimeField(auto_now_add=True)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('paid_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='accounts.olmsuser')),
            ],
            options={
                'db_table': 'guest_sessions',
                'ordering': ['-sign_in_time'],
            },
        ),
    ]
