# Generated by Django 5.1.3 on 2026-07-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_guestsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempreference',
            name='unit',
            field=models.CharField(choices=[('days', 'Days'), ('minutes', 'Minutes'), ('boolean', 'Boolean'), ('text', 'Text'), ('decimal', 'Decimal'), ('integer', 'Integer')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systempreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_preferences', to='accounts.olmsuser'),
        ),
    ]
