# Generated by Django 5.1.3 on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_systempreference_units_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
