# Generated by Django 5.1.3 on 2026-07-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_systempreference_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
