# Generated by Django 5.1.3 on 2026-07-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_guestsession_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='renewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guestsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('renewed', 'Renewed'), ('ended', 'Ended'), ('expired', 'Expired')], default='active', max_length=10),
        ),
    ]
