# Generated by Django 5.1.3 on 2026-07-04 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_guestsession_renewed_alter_guestsession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='e.g. ["member","librarian"]')),
                ('target_member_types', models.JSONField(blank=True, default=list, help_text='e.g. ["student","lecturer"]', null=True)),
                ('send_via', models.JSONField(default=list, help_text='["email","sms"]')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('total_recipients', models.IntegerField(default=0)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('is_new_arrival', models.BooleanField(default=False, help_text='Auto-generated for new book arrivals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_bulk_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_via', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='accounts.bulkmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_message_recipients',
                'ordering': ['-message'],
            },
        ),
    ]
