# Generated by Django 5.1.3 on 2026-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_badgeviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='expiry_notification_sent',
            field=models.BooleanField(default=False, help_text='True if 15-min pre-expiry SMS/email was sent'),
        ),
    ]
