# Generated by Django 5.1.3 on 2026-08-26 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_guest_session_expiry_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManualSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('getting_started', 'Getting Started'), ('borrowing', 'Borrowing Books'), ('returning', 'Returning Books'), ('renewals', 'Renewals'), ('reservations', 'Reservations'), ('fines', 'Fines & Payments'), ('loss', 'Lost Books'), ('softcopy', 'Digital Resources (Softcopies)'), ('notifications', 'Notifications'), ('chat', 'Chat & Support'), ('passwords', 'Password Security'), ('login_attempts', 'Login Attempts & Security'), ('guest', 'Guest Access'), ('ai', 'AI Assistant')], help_text='Unique identifier for this section', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Section title displayed to users', max_length=200)),
                ('icon', models.CharField(default='bi-info-circle', help_text='Bootstrap icon class', max_length=50)),
                ('content', models.TextField(help_text='HTML content for this section')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is visible')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_manual_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Manual Section',
                'verbose_name_plural': 'User Manual Sections',
                'db_table': 'user_manual_sections',
                'ordering': ['order', 'section_key'],
            },
        ),
    ]
