# Generated by Django 5.1.3 on 2026-09-05 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_usermanualsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('acceptance', 'Acceptance of Terms'), ('user_resp', 'User Responsibilities'), ('borrowing', 'Borrowing Rules'), ('fines', 'Fines and Payments'), ('digital', 'Digital Resources'), ('privacy', 'Privacy and Data'), ('conduct', 'Conduct and Discipline'), ('system_usage', 'System Usage'), ('changes', 'Changes to Terms'), ('contact', 'Contact Information'), ('custom', 'Custom Section')], help_text='Section identifier (multiple custom sections allowed)', max_length=50)),
                ('title', models.CharField(help_text='Section heading displayed to users', max_length=200)),
                ('icon', models.CharField(default='bi-file-text', help_text='Bootstrap icon class e.g. bi-shield-check', max_length=50)),
                ('content', models.TextField(help_text='HTML content for this section (tags like <ul>, <p>, <strong> allowed)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_terms_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms & Conditions Section',
                'verbose_name_plural': 'Terms & Conditions Sections',
                'db_table': 'terms_sections',
                'ordering': ['order', 'section_key'],
            },
        ),
    ]
