# Generated by Django 5.1.3 on 2026-04-14 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional: Assign as subcategory under a main category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalog.category'),
        ),
    ]
