# Generated by Django 5.1.3 on 2026-04-15 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_category_to_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Recommended: 1200x400px for carousel', upload_to='media_slides/')),
                ('slide_type', models.CharField(choices=[('carousel', 'Homepage Carousel'), ('advertisement', 'Advertisement'), ('news', 'News Banner'), ('announcement', 'Announcement')], default='carousel', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when clicked', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers display first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for permanent display', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Slide',
                'verbose_name_plural': 'Media Slides',
                'db_table': 'media_slides',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
