# Generated by Django 5.1.3 on 2026-04-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_mediaslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaslide',
            name='slide_type',
            field=models.CharField(choices=[('carousel', 'Homepage Carousel'), ('advertisement', 'Advertisement'), ('news', 'News Banner'), ('announcement', 'Announcement'), ('logo', 'System Logo')], default='carousel', max_length=20),
        ),
    ]
