# Generated by Django 5.1.3 on 2026-04-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_logo_type_to_mediaslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shelf_prefix',
            field=models.CharField(blank=True, help_text='Auto-assigned shelf letter prefix (A, B, C...)', max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, help_text='Optional descriptive name', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=50, help_text='Max number of books')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='catalog.category')),
            ],
            options={
                'db_table': 'shelves',
                'ordering': ['category__shelf_prefix', 'shelf_number'],
                'unique_together': {('category', 'shelf_number')},
            },
        ),
    ]
