# Generated by Django 5.1.3 on 2026-04-17 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_shelf_prefix_and_shelf_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF or document attachment', null=True, upload_to='news/attachments/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image (JPG/PNG)', null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin to top of news feed'),
        ),
        migrations.AddField(
            model_name='news',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional external link (opens in new tab)', max_length=500),
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement'), ('event', 'Event'), ('advertisement', 'Advertisement')], default='news', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL (e.g. https://www.youtube.com/embed/xxx)', max_length=500),
        ),
    ]
