# Generated by Django 5.1.3 on 2026-04-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_news_media_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccessionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(max_length=50, unique=True)),
                ('number', models.PositiveIntegerField(db_index=True, default=0)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deleted_accession_numbers',
                'ordering': ['number'],
            },
        ),
    ]
