# Generated by Django 5.1.3 on 2026-04-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_deleted_accession_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaslide',
            name='bg_color',
            field=models.CharField(blank=True, default='#001a33', help_text='Background color for carousel (hex code, e.g., #001a33)', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaslide',
            name='slide_type',
            field=models.CharField(choices=[('carousel', 'Homepage Carousel'), ('advertisement', 'Advertisement'), ('news', 'News Banner'), ('announcement', 'Announcement'), ('logo', 'System Logo'), ('home_bg', 'Home Page Background')], default='carousel', max_length=20),
        ),
    ]
