# Generated by Django 5.1.3 on 2026-05-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_mediaslide_bg_color_alter_mediaslide_slide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lost_fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
