# Generated by Django 5.1.3 on 2026-05-21 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_rank_lostfine_pwflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='MSICT Online Library', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('location', models.CharField(blank=True, help_text='Location/city', max_length=255)),
                ('copyright_text', models.CharField(default='© 2024 MSICT. All rights reserved.', max_length=255)),
                ('faq_link', models.URLField(blank=True, help_text='FAQ page URL', max_length=500)),
                ('social_facebook', models.URLField(blank=True, max_length=500)),
                ('social_twitter', models.URLField(blank=True, max_length=500)),
                ('social_linkedin', models.URLField(blank=True, max_length=500)),
                ('social_instagram', models.URLField(blank=True, max_length=500)),
                ('additional_links', models.TextField(blank=True, help_text='Additional footer links (one per line: Label|URL)')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Footer Configuration',
                'verbose_name_plural': 'Footer Configurations',
                'db_table': 'footer',
            },
        ),
    ]
