# Generated by Django 5.1.3 on 2026-06-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='prepaid_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prepaid fee for softcopy access (TZS)', max_digits=10),
        ),
    ]
