# Generated by Django 5.1.3 on 2026-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_bookcopy_prepaid_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('reserved', 'Reserved'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='available', max_length=10),
        ),
    ]
