# Generated by Django 5.1.3 on 2026-07-05 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_damage_report_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaslide',
            name='slide_type',
            field=models.CharField(choices=[('carousel', 'Homepage Carousel'), ('advertisement', 'Advertisement'), ('news', 'News Banner'), ('announcement', 'Announcement'), ('logo', 'System Logo'), ('home_bg', 'Home Page Background'), ('login_slideshow', 'Login Page Slideshow')], default='carousel', max_length=20),
        ),
        migrations.CreateModel(
            name='LoginContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('welcome', 'Welcome Heading'), ('motivational', 'Left Side — Motivational Text'), ('ai_reminder', 'Left Side — AI Assistant Reminder'), ('guest_how', 'Right Side — How Guest Account is Created'), ('guest_session', 'Right Side — How Session is Accessed'), ('guest_payment', 'Right Side — Payments & Expiration'), ('guest_upgrade', 'Right Side — Upgrade to Real Member'), ('guest_welcome', 'Right Side — Guest Welcome Words')], max_length=30, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional heading for this section', max_length=255)),
                ('body', models.TextField(help_text='Main text content (HTML allowed)')),
                ('icon', models.CharField(blank=True, default='', help_text='Bootstrap icon class, e.g. bi-robot', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Page Content',
                'verbose_name_plural': 'Login Page Contents',
                'db_table': 'login_content',
                'ordering': ['section'],
            },
        ),
    ]
