# Generated by Django 5.1.3 on 2026-07-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_add_login_slideshow_and_logincontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincontent',
            name='font_size',
            field=models.PositiveIntegerField(default=16, help_text='Font size in px for the body text (10–32)'),
        ),
    ]
