# Generated by Django 5.1.3 on 2026-08-26 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_book_new_arrival_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='file_path',
            field=models.FileField(blank=True, help_text='Softcopy file (PDF only, max 50MB)', null=True, upload_to='ebooks/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='logincontent',
            name='font_size',
            field=models.PositiveIntegerField(default=18, help_text='Font size in px for the body text (10–32)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF or document attachment (max 10MB)', null=True, upload_to='news/attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image (JPG/PNG, max 5MB)', null=True, upload_to='news/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
