# Generated by Django 5.1.3 on 2026-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_bookcopy_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='bg_color',
            field=models.CharField(default='#020617', help_text='Footer background color (hex code, e.g. #020617)', max_length=20),
        ),
    ]
