# Generated by Django 5.1.3 on 2026-05-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_reservation_notified_status_and_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
