# Generated by Django 5.1.3 on 2026-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_fine_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='receipt_no',
            field=models.TextField(blank=True, default=''),
        ),
    ]
