# Generated by Django 5.1.3 on 2026-05-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0004_fine_receipt_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_security_alert',
            field=models.BooleanField(default=False, help_text='Mark as security alert (suspension, lock attempts, suspicious activity)'),
        ),
    ]
