# Generated by Django 5.1.3 on 2026-05-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_rank_lostfine_pwflag'),
        ('circulation', '0005_notification_is_security_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='temp_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardcopy_requests', to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_requests', to='catalog.bookcopy'),
        ),
    ]
