# Generated by Django 5.1.3 on 2026-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0006_hardcopy_flow_temp_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_type',
            field=models.CharField(choices=[('otp', 'OTP'), ('account_lock', 'Account Lock'), ('suspended', 'Suspended'), ('suspicious', 'Suspicious'), ('borrowing', 'Borrowing'), ('approval', 'Approval'), ('fine', 'Fine'), ('overdue', 'Overdue'), ('loss_report', 'Loss Report'), ('loss_fine', 'Loss Fine'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
