# Generated by Django 5.1.3 on 2026-05-20 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0009_alter_notification_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LossReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe how/when the book was lost')),
                ('circumstances', models.CharField(blank=True, help_text='Brief circumstances (e.g. fire, theft, misplaced)', max_length=200)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed – Awaiting Payment'), ('resolved', 'Resolved – Fine Paid'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('librarian_notes', models.TextField(blank=True)),
                ('loss_fine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_report', to='circulation.fine')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loss_reports', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loss_report', to='circulation.borrowingtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loss_reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
