# Generated by Django 5.1.3 on 2026-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0010_lossreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossreport',
            name='authority_reference',
            field=models.CharField(blank=True, help_text='Police/security report reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='lossreport',
            name='authority_reported',
            field=models.BooleanField(default=False, help_text='Whether loss was reported to police/security'),
        ),
        migrations.AddField(
            model_name='lossreport',
            name='date_noticed',
            field=models.DateField(blank=True, help_text='Date the book was noticed missing', null=True),
        ),
        migrations.AddField(
            model_name='lossreport',
            name='last_known_location',
            field=models.CharField(blank=True, help_text='Where the book was last seen', max_length=200),
        ),
    ]
