# Generated by Django 5.1.3 on 2026-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0011_loss_report_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossreport',
            name='date_noticed',
            field=models.DateTimeField(blank=True, help_text='Date/time the book was noticed missing', null=True),
        ),
    ]
