# Generated by Django 5.1.3 on 2026-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0012_loss_report_date_noticed_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingtransaction',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='borrowed', max_length=10),
        ),
    ]
