# Generated by Django 5.1.3 on 2026-06-24 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_bookcopy_prepaid_fee'),
        ('circulation', '0013_alter_borrowingtransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(blank=True, choices=[('otp', 'OTP'), ('account_lock', 'Account Lock'), ('suspended', 'Suspended'), ('suspicious', 'Suspicious'), ('borrowing', 'Borrowing'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('fine', 'Fine'), ('overdue', 'Overdue'), ('loss_report', 'Loss Report'), ('loss_fine', 'Loss Fine'), ('softcopy_link', 'Softcopy Link'), ('softcopy_expiry', 'Softcopy Expiry Warning'), ('password_reminder', 'Password Change Reminder'), ('registration_approved', 'Registration Approved'), ('registration_rejected', 'Registration Rejected')], default='approval', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PrepaidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash')], default='mpesa', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_transactions', to='catalog.bookcopy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prepaid_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftcopyAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('access_url', models.URLField()),
                ('expires_at', models.DateTimeField()),
                ('access_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softcopy_access_logs', to='catalog.bookcopy')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softcopy_access_logs', to='circulation.borrowingtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softcopy_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'softcopy_access_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
