# Generated by Django 5.1.3 on 2026-06-29 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0014_alter_notification_message_type_prepaidtransaction_and_more'),
    ]

    def generate_tokens(apps, schema_editor):
        BorrowingTransaction = apps.get_model('circulation', 'BorrowingTransaction')
        import uuid
        for tx in BorrowingTransaction.objects.filter(access_token__isnull=True):
            tx.access_token = uuid.uuid4()
            tx.save(update_fields=['access_token'])

    operations = [
        migrations.AddField(
            model_name='borrowingtransaction',
            name='access_token',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='borrowingtransaction',
            name='token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(generate_tokens, reverse_code=migrations.RunPython.noop),
    ]
