# Generated by Django 5.1.3 on 2026-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0015_borrowingtransaction_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingtransaction',
            name='access_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
