# Generated by Django 5.1.3 on 2026-07-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_systempreference_units_audit'),
        ('circulation', '0016_alter_borrowingtransaction_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('overdue', 'Overdue Fee'), ('link_fee', 'Softcopy Link Fee'), ('guest_fee', 'Guest Session Fee'), ('loss', 'Loss / Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('reference_table', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_revenue_transactions', to='accounts.olmsuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_transactions', to='accounts.olmsuser')),
            ],
            options={
                'db_table': 'revenue_transactions',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
