# Generated by Django 5.1.3 on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0017_revenuetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('otp', 'OTP'),
                    ('account_lock', 'Account Lock'),
                    ('suspended', 'Suspended'),
                    ('suspicious', 'Suspicious'),
                    ('borrowing', 'Borrowing'),
                    ('approval', 'Approval'),
                    ('rejection', 'Rejection'),
                    ('fine', 'Fine'),
                    ('overdue', 'Overdue'),
                    ('loss_report', 'Loss Report'),
                    ('loss_fine', 'Loss Fine'),
                    ('softcopy_link', 'Softcopy Link'),
                    ('softcopy_expiry', 'Softcopy Expiry Warning'),
                    ('password_reminder', 'Password Change Reminder'),
                    ('registration_approved', 'Registration Approved'),
                    ('registration_rejected', 'Registration Rejected'),
                    ('bulk_message', 'Bulk Message'),
                    ('new_arrival', 'New Arrival'),
                ],
                default='approval',
                max_length=30,
                null=True,
            ),
        ),
    ]
