# Generated by Django 5.1.3 on 2026-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0018_alter_notification_message_type_bulk_and_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidtransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halotel', 'Halotel'), ('card', 'Card'), ('bank', 'Bank'), ('cash', 'Cash')], default='mpesa', max_length=10),
        ),
    ]
