# Generated by Django 5.1.3 on 2026-07-04 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0019_update_prepaid_payment_methods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(blank=True, choices=[('otp', 'OTP'), ('account_lock', 'Account Lock'), ('suspended', 'Suspended'), ('suspicious', 'Suspicious'), ('borrowing', 'Borrowing'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('fine', 'Fine'), ('overdue', 'Overdue'), ('loss_report', 'Loss Report'), ('loss_fine', 'Loss Fine'), ('damage_report', 'Damage Report'), ('damage_fine', 'Damage Fine'), ('softcopy_link', 'Softcopy Link'), ('softcopy_expiry', 'Softcopy Expiry Warning'), ('password_reminder', 'Password Change Reminder'), ('registration_approved', 'Registration Approved'), ('registration_rejected', 'Registration Rejected'), ('bulk_message', 'Bulk Message'), ('new_arrival', 'New Arrival')], default='approval', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='account_type',
            field=models.CharField(choices=[('overdue', 'Overdue Fee'), ('link_fee', 'Softcopy Link Fee'), ('guest_fee', 'Guest Session Fee'), ('loss', 'Loss / Refund'), ('damage', 'Damage Fee')], max_length=20),
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('pages_torn', 'Pages Torn'), ('cover_damaged', 'Cover Damaged'), ('water_damage', 'Water Damage'), ('spine_broken', 'Spine Broken'), ('writing_marking', 'Writing / Marking'), ('missing_pages', 'Missing Pages'), ('other', 'Other')], max_length=20)),
                ('damage_description', models.TextField(blank=True, help_text='Detailed description of damage')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed – Awaiting Payment'), ('resolved', 'Resolved – Fine Paid'), ('dismissed', 'Dismissed')], default='confirmed', max_length=15)),
                ('librarian_notes', models.TextField(blank=True)),
                ('damage_fine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_report', to='circulation.fine')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damage_reports', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damage_report', to='circulation.borrowingtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'damage_reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
