# Generated by Django 5.1.3 on 2026-09-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0022_simplify_softcopy_and_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed – Awaiting Payment'), ('resolved', 'Resolved – Fine Paid'), ('dismissed', 'Dismissed'), ('recovered', 'Recovered')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(blank=True, choices=[('otp', 'OTP'), ('account_lock', 'Account Lock'), ('suspended', 'Suspended'), ('suspicious', 'Suspicious'), ('borrowing', 'Borrowing'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('fine', 'Fine'), ('overdue', 'Overdue'), ('loss_report', 'Loss Report'), ('loss_fine', 'Loss Fine'), ('damage_report', 'Damage Report'), ('damage_fine', 'Damage Fine'), ('softcopy_link', 'Softcopy Link'), ('softcopy_expiry', 'Softcopy Expiry Warning'), ('guest_session_expiry_warning', 'Guest Session Expiry Warning'), ('password_reminder', 'Password Change Reminder'), ('registration_approved', 'Registration Approved'), ('registration_rejected', 'Registration Rejected'), ('bulk_message', 'Bulk Message'), ('new_arrival', 'New Arrival')], default='approval', max_length=30, null=True),
        ),
    ]
